/*
 * Copyright 2022 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;

[Serializable]
public class CommandResult
{
    // True if the command request was validated and the
    // command 'succeeded'
    public bool commandSuccess;
    // If commandValidated is false, this will contain a diagnostic message as to why the
    // validation failed. If true, this will contain a diagnostic message summarizing the
    // verdict signals from Play Identity. This is intended for informational purposes in
    // this sample, you would not normally sent verdict details back to the client
    public string diagnosticMessage;
    // If a command request is validated using a token generated by Play Integrity
    // expressToken in this field is returned by the server for use with
    // future command requests instead of a Play Integrity token. This avoids
    // calling Play Integrity too frequently. The client should not persistently store
    // this token, and should be prepared to receive a failure to validate with a 'token expired'
    // message, in which case it should repeat the command request with a new Play Integrity token
    // to validate and obtain a fresh expressToken
    public string expressToken;
}
