/*
 * Copyright 2022 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;

[Serializable]
public class ServerCommand
{
    public ServerCommand(string command, string token)
    {
        commandString = command;
        tokenString = token;
    }

    public string commandString;
    // This can be either the token string generated by Play Integrity
    // or the 'validated' token returned by a previous command that
    // successfully passed integrity checks
    public string tokenString;
}
